server:
  port: 8080

spring:
  application:
    name: locations
  devtools:
    restart:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:2345/locations_db?createDatabaseIfNotExist=true&useSSL=false
    username: developer
    password: 01092209
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false
  flyway:
    path: classpath:db/migration
    schemas: location
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    use-root-path: true
    # path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
