CREATE TABLE IF NOT EXISTS locations.annexes (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) UNIQUE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  created_by VARCHAR(100) NOT NULL,
  updated_at TIMESTAMP DEFAULT NULL,
  updated_by VARCHAR(100) DEFAULT NULL,
  deleted BOOLEAN DEFAULT FALSE NOT NULL
);
